const day10 = COURSE[2].lessons[2];

Object.assign(day10, {
  published: true,
  summary: "Measure surprise, uncertainty, coding cost, and distribution mismatch. Learn the information-theory language behind cross-entropy, KL divergence, mutual information, perplexity, and variational methods.",
  explanation: "Information theory turns uncertainty into quantities that we can calculate. A rare event carries more surprise than a common event. Entropy averages that surprise under one distribution. Cross-entropy measures the cost of using one distribution to encode data generated by another. KL divergence isolates the extra cost caused by mismatch. These ideas appear directly in classification losses, language-model perplexity, representation learning, and variational inference.",
  topics: [
    "Self-information",
    "Entropy",
    "Binary entropy",
    "Joint and conditional entropy",
    "Cross-entropy",
    "KL divergence",
    "Mutual information",
    "Conditional mutual information",
    "Entropy chain rule",
    "Coding interpretation",
    "Maximum entropy",
    "Perplexity",
    "Cross-entropy as negative log-likelihood",
    "Jensen’s inequality",
    "Gibbs’ inequality",
    "Categorical and Gaussian entropy",
    "Information bottleneck",
    "Feature selection",
    "Variational inference",
    "Why KL is not symmetric"
  ],
  sections: [
    {
      id: "self-information",
      title: "1. Self-information measures the surprise of one event",
      html: String.raw`
        <p>Start with one event that has probability \(p\). If the event is almost certain, observing it tells you little. If the event is rare, observing it tells you more.</p>
        <p>The <strong>self-information</strong> of an event with probability \(p\) is</p>
        <p>\[I(p)=-\log p.\]</p>
        <p>The logarithm base sets the unit. Base 2 gives <strong>bits</strong>. The natural logarithm gives <strong>nats</strong>. ML papers often use natural logs because derivatives are convenient.</p>
        <h3>Numerical examples</h3>
        <p>If \(p=1\), then</p>
        <p>\[I(1)=-\log 1=0.\]</p>
        <p>A certain event carries no surprise.</p>
        <p>If \(p=1/2\) and we use base 2, then</p>
        <p>\[I(1/2)=-\log_2(1/2)=1\text{ bit}.\]</p>
        <p>If \(p=1/8\), then</p>
        <p>\[I(1/8)=3\text{ bits}.\]</p>
        <p>The event with probability \(1/8\) is more surprising than the event with probability \(1/2\).</p>
        <div class="paper-connection">
          <strong>Why this matters for ML papers.</strong> The negative log-probability of the observed target is exactly a surprise score. If a classifier assigns probability \(0.9\) to the correct class, its loss is small. If it assigns probability \(0.01\), its loss is large.
        </div>
        <div class="shape-check">
          <strong>Notation warning.</strong> \(-\log p\) is a scalar. The probability \(p\) must satisfy \(0&lt;p\le1\). As \(p\to0\), the information goes to infinity.
        </div>
      `
    },
    {
      id: "entropy",
      title: "2. Entropy is the average surprise under a distribution",
      html: String.raw`
        <p>Self-information describes one outcome. <strong>Entropy</strong> averages self-information over all possible outcomes.</p>
        <p>For a discrete random variable \(X\) with probabilities \(p(x)\),</p>
        <p>\[H(X)=-\sum_x p(x)\log p(x).\]</p>
        <p>You can also write</p>
        <p>\[H(X)=\mathbb{E}_{X\sim p}[-\log p(X)].\]</p>
        <p>This notation means: sample \(X\) from distribution \(p\), compute the surprise \(-\log p(X)\), and average.</p>
        <h3>Fair coin</h3>
        <p>For a fair coin, \(p(H)=p(T)=1/2\). Using base 2,</p>
        <p>\[H(X)=-\frac12\log_2\frac12-\frac12\log_2\frac12=1\text{ bit}.\]</p>
        <h3>Biased coin</h3>
        <p>If \(p(H)=0.9\) and \(p(T)=0.1\), then</p>
        <p>\[H(X)=-0.9\log_2 0.9-0.1\log_2 0.1\approx0.469\text{ bits}.\]</p>
        <p>The biased coin has lower entropy because its outcome is easier to predict.</p>
        <div class="paper-connection">
          <strong>ML connection.</strong> Entropy is often used to quantify predictive uncertainty. A classifier output \((0.99,0.01)\) has low entropy. An output \((0.5,0.5)\) has high entropy.
        </div>
        <div class="shape-check">
          <strong>Common mistake.</strong> High entropy does not mean the distribution is wrong. It means the distribution itself is uncertain or spread out. Accuracy and entropy answer different questions.
        </div>
      `
    },
    {
      id: "binary-entropy",
      title: "3. Binary entropy shows how uncertainty changes with one probability",
      html: String.raw`
        <p>A Bernoulli random variable has two outcomes. Let \(P(X=1)=p\) and \(P(X=0)=1-p\). Its entropy is</p>
        <p>\[H_{\mathrm{bin}}(p)=-p\log p-(1-p)\log(1-p).\]</p>
        <p>The entropy is smallest at \(p=0\) or \(p=1\), because the outcome is certain. It is largest at \(p=1/2\), because the two outcomes are equally likely.</p>
        <h3>Three values</h3>
        <p>Using base 2:</p>
        <p>\[H_{\mathrm{bin}}(0)=0,\qquad H_{\mathrm{bin}}(0.5)=1,\qquad H_{\mathrm{bin}}(0.9)\approx0.469.\]</p>
        <p>Notice the symmetry:</p>
        <p>\[H_{\mathrm{bin}}(p)=H_{\mathrm{bin}}(1-p).\]</p>
        <div class="paper-connection">
          <strong>ML connection.</strong> Binary classification probabilities often appear as Bernoulli parameters. Entropy of the prediction can be used as a rough uncertainty score for active learning, confidence filtering, or pseudo-label selection.
        </div>
        <div class="shape-check">
          <strong>Boundary convention.</strong> The term \(0\log0\) is defined by its limit as 0. The limit is 0, so deterministic outcomes have entropy 0.
        </div>
      `
    },
    {
      id: "joint-conditional-entropy",
      title: "4. Joint and conditional entropy separate total uncertainty from remaining uncertainty",
      html: String.raw`
        <p>For two discrete variables \(X\) and \(Y\), the <strong>joint entropy</strong> is</p>
        <p>\[H(X,Y)=-\sum_x\sum_y p(x,y)\log p(x,y).\]</p>
        <p>It measures uncertainty about the pair \((X,Y)\).</p>
        <p>The <strong>conditional entropy</strong> of \(Y\) given \(X\) is</p>
        <p>\[H(Y\mid X)=-\sum_x p(x)\sum_y p(y\mid x)\log p(y\mid x).\]</p>
        <p>Read this as: after observing \(X\), how much uncertainty about \(Y\) remains on average?</p>
        <h3>Small example</h3>
        <p>Suppose \(X\) is a fair bit and \(Y=X\) exactly. Then knowing \(X\) determines \(Y\). Therefore,</p>
        <p>\[H(Y\mid X)=0.\]</p>
        <p>Without observing \(X\), \(Y\) is still a fair bit, so</p>
        <p>\[H(Y)=1\text{ bit}.\]</p>
        <p>If instead \(X\) and \(Y\) are independent fair bits, observing \(X\) tells us nothing about \(Y\), and</p>
        <p>\[H(Y\mid X)=H(Y)=1\text{ bit}.\]</p>
        <div class="paper-connection">
          <strong>ML connection.</strong> Conditional entropy appears when a representation, context, or input reduces uncertainty about a label or next token. A useful representation should often make the target easier to predict.
        </div>
      `
    },
    {
      id: "cross-entropy",
      title: "5. Cross-entropy measures the cost of predicting with the wrong distribution",
      html: String.raw`
        <p>Suppose the true data distribution is \(p\), but your model predicts distribution \(q\). The <strong>cross-entropy</strong> from \(p\) to \(q\) is</p>
        <p>\[H(p,q)=-\sum_x p(x)\log q(x).\]</p>
        <p>The expectation form is</p>
        <p>\[H(p,q)=\mathbb{E}_{X\sim p}[-\log q(X)].\]</p>
        <p>The data are drawn according to \(p\), but the surprise is measured using the model probabilities \(q\).</p>
        <h3>Numerical example</h3>
        <p>Let the true binary distribution be</p>
        <p>\[p=(0.75,0.25).\]</p>
        <p>Let the model predict</p>
        <p>\[q=(0.60,0.40).\]</p>
        <p>Using natural logs,</p>
        <p>\[H(p,q)=-0.75\log0.60-0.25\log0.40\approx0.612.\]</p>
        <p>The entropy of the true distribution is</p>
        <p>\[H(p)=-0.75\log0.75-0.25\log0.25\approx0.562.\]</p>
        <p>The model pays extra cost because \(q\ne p\).</p>
        <h3>One-hot classification</h3>
        <p>If the true label is class \(k\), then the target vector is one-hot: \(y_k=1\) and all other entries are 0. The cross-entropy becomes</p>
        <p>\[L=-\sum_i y_i\log q_i=-\log q_k.\]</p>
        <div class="paper-connection">
          <strong>Shape reasoning.</strong> For a batch of \(B\) examples and \(C\) classes, logits and predicted probabilities usually have shape \(B\times C\). Per-example cross-entropy reduces the class axis and produces \(B\) scalar losses. A final mean can reduce the batch axis to one scalar.
        </div>
        <div class="shape-check">
          <strong>Common notation trap.</strong> Some authors write \(H(p,q)\) for cross-entropy. Others write only \(H(q)\) when the target distribution is understood. Always inspect the definition.
        </div>
      `
    },
    {
      id: "kl-divergence",
      title: "6. KL divergence isolates the extra cost caused by distribution mismatch",
      html: String.raw`
        <p>The <strong>Kullback-Leibler divergence</strong> from \(p\) to \(q\) is</p>
        <p>\[D_{\mathrm{KL}}(p\|q)=\sum_x p(x)\log\frac{p(x)}{q(x)}.\]</p>
        <p>It can also be written as</p>
        <p>\[D_{\mathrm{KL}}(p\|q)=H(p,q)-H(p).\]</p>
        <p>This identity is important. Cross-entropy contains two parts:</p>
        <p>\[\boxed{H(p,q)=H(p)+D_{\mathrm{KL}}(p\|q)}.\]</p>
        <p>The entropy \(H(p)\) is the unavoidable uncertainty in the true distribution. The KL term is the additional cost caused by using \(q\) instead of \(p\).</p>
        <h3>Continue the previous example</h3>
        <p>We found</p>
        <p>\[H(p,q)\approx0.612,\qquad H(p)\approx0.562.\]</p>
        <p>Therefore,</p>
        <p>\[D_{\mathrm{KL}}(p\|q)\approx0.050.\]</p>
        <p>If \(p=q\), then</p>
        <p>\[D_{\mathrm{KL}}(p\|q)=0.\]</p>
        <div class="paper-connection">
          <strong>ML connection.</strong> Knowledge distillation can minimize KL divergence between a teacher distribution and a student distribution. Variational inference also uses KL terms to compare an approximate posterior with a target or prior distribution.
        </div>
        <div class="shape-check">
          <strong>Support warning.</strong> If \(p(x)&gt;0\) but \(q(x)=0\), then the KL divergence is infinite because the model assigns zero probability to an event that can actually occur.
        </div>
      `
    }
  ],
  examples: [],
  practice: []
});
